In [2]:
import numpy as np
import matplotlib.pyplot as plt
import quandl as qdl
import pandas as pd

from sklearn import preprocessing, model_selection
from sklearn.tree import DecisionTreeRegressor
from sklearn.linear_model import LinearRegression, SGDRegressor
from sklearn.metrics import mean_absolute_error, mean_squared_error, r2_score

plt.style.use('bmh')

We do now know that learning the parameters of a prediction function and testing it on the same data is a methodological mistake. Our model that would just repeat the labels of the samples that it has just seen would have a perfect score but would fail to predict anything useful on unseen data. In few wors its called overfitting. So we manipulate our data according some rules to avoid this situation as much as we can in (supervised) machine learning. We hold out part of the available data as a test set

In [3]:
X_train, X_test, y_train, y_test = model_selection.train_test_split(X, y, test_size = 0.25)
print('length of X_train and x_test: ', len(X_train), len(X_test))

NameError: name 'X' is not defined

But wait, whats going in in <code>**train_test_split**</code> ? What we do know is that it splits provided X,y into two sizes data bathches. And we are interested in the train data set quality. But how to asses training data quality ? <code>**Randomness !**</code>

In [4]:
X_a, y_a = np.arange(20).reshape((10, 2)), range(10)

In [5]:
print(f'X matrix:\n{X_a}')
print(f'y vector:\n{y_a}')

X matrix:
[[ 0  1]
 [ 2  3]
 [ 4  5]
 [ 6  7]
 [ 8  9]
 [10 11]
 [12 13]
 [14 15]
 [16 17]
 [18 19]]
y vector:
range(0, 10)


In [19]:
X_a_train, X_a_test, y_a_train, y_a_test = model_selection.train_test_split(X_a, y_a, shuffle=False)
print(f'X train matrix:\n{X_a_train}')
print(f'y tain vector:\n{y_a_train}')
print(f'X test matrix:\n{X_a_test}')
print(f'y test vector:\n{y_a_test}')

X train matrix:
[[ 0  1]
 [ 2  3]
 [ 4  5]
 [ 6  7]
 [ 8  9]
 [10 11]
 [12 13]]
y tain vector:
[0, 1, 2, 3, 4, 5, 6]
X test matrix:
[[14 15]
 [16 17]
 [18 19]]
y test vector:
[7, 8, 9]


Lets give to our split method a<code>**pseudo random generator**</code> with flag <code>**random_state**</code>
This Controls the shuffling applied to the data before applying the split. <br>

<code>**Watch:**</code><br>
https://youtu.be/GtOt7EBNEwQ

In [17]:
X_a_train, X_a_test, y_a_train, y_a_test = model_selection.train_test_split(X_a, y_a, random_state=0)
print(f'X matrix:\n{X_a_train}')
print(f'y vector:\n{y_a_train}')

X matrix:
[[18 19]
 [ 2  3]
 [12 13]
 [14 15]
 [ 6  7]
 [ 0  1]
 [10 11]]
y vector:
[9, 1, 6, 7, 3, 0, 5]


In [ ]:
rnd = np.random.RandomState(seed=123)
X = rnd.uniform(low=0.0, high=1.0, size=(3, 5))
X

In [ ]:
X[1, 0:]

In [ ]:
y = np.linspace(0, 12, 5)
y

In [ ]:
y_vector = y[:, np.newaxis]

In [ ]:
# DEAL WITH NAN
df.dropna(inplace=True)
# df.tail()
#df.fillna(value=-99999, inplace=True)
# df.tail(45)

#df['prediction'].fillna(df['prediction'].mean(), inplace=True)
#df.fillna(value=-99999, inplace=True)

In [ ]:
size = int(volume.size/4)
plt.hist(volume, bins=size, density=True)
xt = plt.xticks()[0]  
xmin, xmax = min(xt), max(xt)  
space = np.linspace(xmin, xmax, len(volume))

In [ ]:
# from __linear_regression_X(test_prep_a)

xexs  = X_test[0,:]
theta = [-7.68383132, 0.78109191, 0.17592058]
y = 118.46 + theta[0]*xexs[0] + theta[1]*xexs[1] + theta[2]*xexs[2]
print(y)
print(y_test[0])